# Calming and Beautiful Dark Themes Registry for Zine Scraper

THEMES = {
    "tokyo-night-storm": {
        "info": "#7dcfff",
        "warning": "#e0af68",
        "error": "bold #f7768e",
        "success": "bold #9ece6a",
        "site": "bold #bb9af7",
        "title": "bold #c0caf5",
        "count": "bold #e0af68",
        "menu": "#7aa2f7",
        "selected": "bold #bb9af7",
        "unselected": "#565f89",
        "tree.line": "#565f89",
        "sexy_pink": "bold #bb9af7"
    },
    "catppuccin": {
        "info": "#89b4fa",
        "warning": "#f9e2af",
        "error": "bold #f38ba8",
        "success": "bold #a6e3a1",
        "site": "bold #cba6f7",
        "title": "bold #cdd6f4",
        "count": "bold #f9e2af",
        "menu": "#74c7ec",
        "selected": "bold #cba6f7",
        "unselected": "#585b70",
        "tree.line": "#585b70",
        "sexy_pink": "bold #cba6f7"
    },
    "github-dark": {
        "info": "#39c5cf",
        "warning": "#d29922",
        "error": "bold #f85149",
        "success": "bold #3fb950",
        "site": "bold #58a6ff",
        "title": "bold #c9d1d9",
        "count": "bold #d29922",
        "menu": "#58a6ff",
        "selected": "bold #58a6ff",
        "unselected": "#484f58",
        "tree.line": "#484f58",
        "sexy_pink": "bold #bc8cff"
    },
    "dracula": {
        "info": "#8be9fd",
        "warning": "#f1fa8c",
        "error": "bold #ff5555",
        "success": "bold #50fa7b",
        "site": "bold #ff79c6",
        "title": "bold #f8f8f2",
        "count": "bold #f1fa8c",
        "menu": "#bd93f9",
        "selected": "bold #ff79c6",
        "unselected": "#6272a4",
        "tree.line": "#6272a4",
        "sexy_pink": "bold #ff79c6"
    },
    "nord": {
        "info": "#8fbcbb",
        "warning": "#ebcb8b",
        "error": "bold #bf616a",
        "success": "bold #a3be8c",
        "site": "bold #88c0d0",
        "title": "bold #d8dee9",
        "count": "bold #ebcb8b",
        "menu": "#81a1c1",
        "selected": "bold #88c0d0",
        "unselected": "#4c566a",
        "tree.line": "#4c566a",
        "sexy_pink": "bold #b48ead"
    },
    "one-dark": {
        "info": "#61afef",
        "warning": "#d19a66",
        "error": "bold #e06c75",
        "success": "bold #98c379",
        "site": "bold #c678dd",
        "title": "bold #abb2bf",
        "count": "bold #d19a66",
        "menu": "#61afef",
        "selected": "bold #c678dd",
        "unselected": "#5c6370",
        "tree.line": "#5c6370",
        "sexy_pink": "bold #c678dd"
    },
    "everforest": {
        "info": "#7fbbb3",
        "warning": "#dbbc7f",
        "error": "bold #e67e80",
        "success": "bold #a7c080",
        "site": "bold #d699b6",
        "title": "bold #d3c6aa",
        "count": "bold #dbbc7f",
        "menu": "#83c092",
        "selected": "bold #d699b6",
        "unselected": "#7a8478",
        "tree.line": "#7a8478",
        "sexy_pink": "bold #d699b6"
    },
    "gruvbox-dark": {
        "info": "#83a598",
        "warning": "#fabd2f",
        "error": "bold #fb4934",
        "success": "bold #b8bb26",
        "site": "bold #d3869b",
        "title": "bold #ebdbb2",
        "count": "bold #fabd2f",
        "menu": "#8ec07c",
        "selected": "bold #d3869b",
        "unselected": "#928374",
        "tree.line": "#928374",
        "sexy_pink": "bold #d3869b"
    },
    "rose-pine": {
        "info": "#9ccfd8",
        "warning": "#f6c177",
        "error": "bold #eb6f92",
        "success": "bold #ebbcba",
        "site": "bold #c4a7e7",
        "title": "bold #e0def4",
        "count": "bold #f6c177",
        "menu": "#c4a7e7",
        "selected": "bold #c4a7e7",
        "unselected": "#6e6a86",
        "tree.line": "#6e6a86",
        "sexy_pink": "bold #ebbcba"
    },
    "night-owl": {
        "info": "#7fdbca",
        "warning": "#ecc48d",
        "error": "bold #ef5350",
        "success": "bold #22da6e",
        "site": "bold #c792ea",
        "title": "bold #d6deeb",
        "count": "bold #ecc48d",
        "menu": "#82aaff",
        "selected": "bold #c792ea",
        "unselected": "#5f7e97",
        "tree.line": "#5f7e97",
        "sexy_pink": "bold #c792ea"
    },
    "ayu-dark": {
        "info": "#39bae6",
        "warning": "#ffb454",
        "error": "bold #ff3333",
        "success": "bold #c2d94c",
        "site": "bold #f29668",
        "title": "bold #e0e0e0",
        "count": "bold #ffb454",
        "menu": "#39bae6",
        "selected": "bold #f29718",
        "unselected": "#5c6773",
        "tree.line": "#5c6773",
        "sexy_pink": "bold #f29718"
    },
    "monokai-pro": {
        "info": "#78dce8",
        "warning": "#ffd866",
        "error": "bold #ff6188",
        "success": "bold #a9dc76",
        "site": "bold #ab9df2",
        "title": "bold #fcfcfa",
        "count": "bold #ffd866",
        "menu": "#fc9867",
        "selected": "bold #ab9df2",
        "unselected": "#727072",
        "tree.line": "#727072",
        "sexy_pink": "bold #ff6188"
    },
    "solarized-dark": {
        "info": "#268bd2",
        "warning": "#b58900",
        "error": "bold #dc322f",
        "success": "bold #859900",
        "site": "bold #6c71c4",
        "title": "bold #93a1a1",
        "count": "bold #b58900",
        "menu": "#2aa198",
        "selected": "bold #2aa198",
        "unselected": "#586e75",
        "tree.line": "#586e75",
        "sexy_pink": "bold #6c71c4"
    },
    "horizon": {
        "info": "#25b0bc",
        "warning": "#f9cec3",
        "error": "bold #e95678",
        "success": "bold #29d390",
        "site": "bold #b877db",
        "title": "bold #e1e2e7",
        "count": "bold #f9cec3",
        "menu": "#f9cec3",
        "selected": "bold #b877db",
        "unselected": "#6c6f93",
        "tree.line": "#6c6f93",
        "sexy_pink": "bold #e95678"
    },
    "oxocarbon": {
        "info": "#78a9ff",
        "warning": "#ff7eb6",
        "error": "bold #fa4d56",
        "success": "bold #42be65",
        "site": "bold #be95ff",
        "title": "bold #f2f4f8",
        "count": "bold #ff7eb6",
        "menu": "#82cfff",
        "selected": "bold #be95ff",
        "unselected": "#525252",
        "tree.line": "#393939",
        "sexy_pink": "bold #be95ff"
    },
    "synthwave-84": {
        "info": "#36f9f6",
        "warning": "#fede5d",
        "error": "bold #fe4450",
        "success": "bold #72f1b8",
        "site": "bold #ff7edb",
        "title": "bold #f0eff1",
        "count": "bold #fede5d",
        "menu": "#fe4450",
        "selected": "bold #ff7edb",
        "unselected": "#614d85",
        "tree.line": "#493566",
        "sexy_pink": "bold #ff7edb"
    },
    "cyberpunk": {
        "info": "#00f0ff",
        "warning": "#ffe600",
        "error": "bold #ff0055",
        "success": "bold #05ffa1",
        "site": "bold #ff007f",
        "title": "bold #ffffff",
        "count": "bold #ffe600",
        "menu": "#00f0ff",
        "selected": "bold #ff007f",
        "unselected": "#4a4a75",
        "tree.line": "#2d2d4d",
        "sexy_pink": "bold #ff007f"
    },
    "neon-night": {
        "info": "#00e5ff",
        "warning": "#ffea00",
        "error": "bold #ff1744",
        "success": "bold #00e676",
        "site": "bold #d500f9",
        "title": "bold #eceff1",
        "count": "bold #ffea00",
        "menu": "#2979ff",
        "selected": "bold #d500f9",
        "unselected": "#455a64",
        "tree.line": "#37474f",
        "sexy_pink": "bold #f50057"
    },
    "cobalt2": {
        "info": "#0088ff",
        "warning": "#ffc600",
        "error": "bold #ff0000",
        "success": "bold #3ad900",
        "site": "bold #ff9d00",
        "title": "bold #ffffff",
        "count": "bold #ffc600",
        "menu": "#0088ff",
        "selected": "bold #ff9d00",
        "unselected": "#0050a0",
        "tree.line": "#003870",
        "sexy_pink": "bold #ff0078"
    },
    "kanagawa": {
        "info": "#7e9cd8",
        "warning": "#e6c384",
        "error": "bold #c34043",
        "success": "bold #76946a",
        "site": "bold #957fb8",
        "title": "bold #dcd7ba",
        "count": "bold #e6c384",
        "menu": "#7e9cd8",
        "selected": "bold #957fb8",
        "unselected": "#54546d",
        "tree.line": "#363646",
        "sexy_pink": "bold #d27e99"
    },
    "andromeda": {
        "info": "#00e5ff",
        "warning": "#ffe66d",
        "error": "bold #ff4e69",
        "success": "bold #09f7a0",
        "site": "bold #c678dd",
        "title": "bold #e5e5e5",
        "count": "bold #ffe66d",
        "menu": "#00e5ff",
        "selected": "bold #c678dd",
        "unselected": "#5b6272",
        "tree.line": "#3a3f4d",
        "sexy_pink": "bold #f14e96"
    },
    "palenight": {
        "info": "#89ddff",
        "warning": "#ffcb6b",
        "error": "bold #ff5370",
        "success": "bold #c3e88d",
        "site": "bold #c792ea",
        "title": "bold #a6accd",
        "count": "bold #ffcb6b",
        "menu": "#82aaff",
        "selected": "bold #c792ea",
        "unselected": "#676e95",
        "tree.line": "#444a69",
        "sexy_pink": "bold #f07178"
    },
    "material-darker": {
        "info": "#80cbc4",
        "warning": "#ffcb6b",
        "error": "bold #ff5370",
        "success": "bold #c3e88d",
        "site": "bold #c792ea",
        "title": "bold #eeffff",
        "count": "bold #ffcb6b",
        "menu": "#82aaff",
        "selected": "bold #c792ea",
        "unselected": "#616161",
        "tree.line": "#424242",
        "sexy_pink": "bold #ff5370"
    },
    "shades-of-purple": {
        "info": "#a599e9",
        "warning": "#ffe47e",
        "error": "bold #ff628c",
        "success": "bold #a5ff90",
        "site": "bold #fb94ff",
        "title": "bold #ffffff",
        "count": "bold #ffe47e",
        "menu": "#9e86ff",
        "selected": "bold #fb94ff",
        "unselected": "#6c60a4",
        "tree.line": "#493e7d",
        "sexy_pink": "bold #fb94ff"
    },
    "deep-ocean": {
        "info": "#4fd6be",
        "warning": "#ffc777",
        "error": "bold #ff757f",
        "success": "bold #c3e88d",
        "site": "bold #fca7ea",
        "title": "bold #c8d3f5",
        "count": "bold #ffc777",
        "menu": "#82aaff",
        "selected": "bold #fca7ea",
        "unselected": "#444a73",
        "tree.line": "#2d314e",
        "sexy_pink": "bold #fca7ea"
    },
    "tokyonight-night": {
        "info": "#7dcfff",
        "warning": "#e0af68",
        "error": "bold #f7768e",
        "success": "bold #9ece6a",
        "site": "bold #bb9af7",
        "title": "bold #c0caf5",
        "count": "bold #e0af68",
        "menu": "#7aa2f7",
        "selected": "bold #bb9af7",
        "unselected": "#414868",
        "tree.line": "#2ac3de",
        "sexy_pink": "bold #bb9af7"
    },
    "catppuccin-macchiato": {
        "info": "#8aadf4",
        "warning": "#eed49f",
        "error": "bold #ed8796",
        "success": "bold #a6da95",
        "site": "bold #c6a0f6",
        "title": "bold #cad3f5",
        "count": "bold #eed49f",
        "menu": "#7dc4e4",
        "selected": "bold #c6a0f6",
        "unselected": "#5b6078",
        "tree.line": "#494d64",
        "sexy_pink": "bold #f5bde6"
    },
    "catppuccin-frappe": {
        "info": "#8caaee",
        "warning": "#e5c890",
        "error": "bold #e78284",
        "success": "bold #a6d189",
        "site": "bold #ca9ee6",
        "title": "bold #c6d0f5",
        "count": "bold #e5c890",
        "menu": "#85c1dc",
        "selected": "bold #ca9ee6",
        "unselected": "#626880",
        "tree.line": "#51576d",
        "sexy_pink": "bold #f4b8e4"
    },
    "rose-pine-moon": {
        "info": "#9ccfd8",
        "warning": "#f6c177",
        "error": "bold #eb6f92",
        "success": "bold #ea9a97",
        "site": "bold #c4a7e7",
        "title": "bold #e0def4",
        "count": "bold #f6c177",
        "menu": "#3e8fb0",
        "selected": "bold #c4a7e7",
        "unselected": "#59546d",
        "tree.line": "#44415a",
        "sexy_pink": "bold #eb6f92"
    },
    "dracula-purple": {
        "info": "#a4ffff",
        "warning": "#ffff80",
        "error": "bold #ff6e6e",
        "success": "bold #69ff94",
        "site": "bold #ff92d0",
        "title": "bold #f8f8f2",
        "count": "bold #ffff80",
        "menu": "#d6acff",
        "selected": "bold #ff92d0",
        "unselected": "#6272a4",
        "tree.line": "#44475a",
        "sexy_pink": "bold #ff92d0"
    },
    "moonlight": {
        "info": "#04d9ff",
        "warning": "#ffc777",
        "error": "bold #ff5370",
        "success": "bold #baacff",
        "site": "bold #fca7ea",
        "title": "bold #c8d3f5",
        "count": "bold #ffc777",
        "menu": "#82aaff",
        "selected": "bold #fca7ea",
        "unselected": "#444a73",
        "tree.line": "#2e3440",
        "sexy_pink": "bold #b4f9f8"
    },
    "outrun-neon": {
        "info": "#00f0ff",
        "warning": "#ffcc00",
        "error": "bold #ff0055",
        "success": "bold #00ff66",
        "site": "bold #ff00aa",
        "title": "bold #ffffff",
        "count": "bold #ffcc00",
        "menu": "#9900ff",
        "selected": "bold #ff00aa",
        "unselected": "#552277",
        "tree.line": "#331144",
        "sexy_pink": "bold #ff00aa"
    },
    "laserwave": {
        "info": "#40b4c4",
        "warning": "#ffe261",
        "error": "bold #eb647f",
        "success": "bold #b4dce1",
        "site": "bold #b180d7",
        "title": "bold #ffffff",
        "count": "bold #ffe261",
        "menu": "#74dfc4",
        "selected": "bold #b180d7",
        "unselected": "#504764",
        "tree.line": "#39324b",
        "sexy_pink": "bold #eb647f"
    },
    "velvet-violet": {
        "info": "#82b1ff",
        "warning": "#ffd54f",
        "error": "bold #ff5252",
        "success": "bold #69f0ae",
        "site": "bold #e040fb",
        "title": "bold #ede7f6",
        "count": "bold #ffd54f",
        "menu": "#b388ff",
        "selected": "bold #e040fb",
        "unselected": "#512da8",
        "tree.line": "#311b92",
        "sexy_pink": "bold #ff4081"
    },
    "electric-blue": {
        "info": "#00b0ff",
        "warning": "#ffd600",
        "error": "bold #ff1744",
        "success": "bold #00e676",
        "site": "bold #7c4dff",
        "title": "bold #e1f5fe",
        "count": "bold #ffd600",
        "menu": "#40c4ff",
        "selected": "bold #7c4dff",
        "unselected": "#0277bd",
        "tree.line": "#01579b",
        "sexy_pink": "bold #00e5ff"
    },
    "emerald-dark": {
        "info": "#26a69a",
        "warning": "#ffee58",
        "error": "bold #ef5350",
        "success": "bold #66bb6a",
        "site": "bold #ab47bc",
        "title": "bold #e0f2f1",
        "count": "bold #ffee58",
        "menu": "#26c6da",
        "selected": "bold #ab47bc",
        "unselected": "#00695c",
        "tree.line": "#004d40",
        "sexy_pink": "bold #26a69a"
    },
    "crimson-dusk": {
        "info": "#ff8a80",
        "warning": "#ffd180",
        "error": "bold #ff5252",
        "success": "bold #b9f6ca",
        "site": "bold #ff4081",
        "title": "bold #ffebee",
        "count": "bold #ffd180",
        "menu": "#ff80ab",
        "selected": "bold #ff4081",
        "unselected": "#b71c1c",
        "tree.line": "#880e4f",
        "sexy_pink": "bold #ff4081"
    },
    "amber-gold": {
        "info": "#ffe082",
        "warning": "#ffb74d",
        "error": "bold #ff5252",
        "success": "bold #aed581",
        "site": "bold #ffd54f",
        "title": "bold #fff8e1",
        "count": "bold #ffb74d",
        "menu": "#ffca28",
        "selected": "bold #ffd54f",
        "unselected": "#f57f17",
        "tree.line": "#e65100",
        "sexy_pink": "bold #ffb74d"
    },
    "copper-oxide": {
        "info": "#80deea",
        "warning": "#ffcc80",
        "error": "bold #ff8a65",
        "success": "bold #a5d6a7",
        "site": "bold #b0bec5",
        "title": "bold #eceff1",
        "count": "bold #ffcc80",
        "menu": "#4dd0e1",
        "selected": "bold #b0bec5",
        "unselected": "#455a64",
        "tree.line": "#263238",
        "sexy_pink": "bold #80deea"
    },
    "midnight-synth": {
        "info": "#00e5ff",
        "warning": "#ffea00",
        "error": "bold #ff1744",
        "success": "bold #00e676",
        "site": "bold #ea80fc",
        "title": "bold #ffffff",
        "count": "bold #ffea00",
        "menu": "#651fff",
        "selected": "bold #ea80fc",
        "unselected": "#4a148c",
        "tree.line": "#311b92",
        "sexy_pink": "bold #ea80fc"
    },
    "nordic-frost": {
        "info": "#8fbcbb",
        "warning": "#d8dee9",
        "error": "bold #bf616a",
        "success": "bold #a3be8c",
        "site": "bold #81a1c1",
        "title": "bold #e5e9f0",
        "count": "bold #88c0d0",
        "menu": "#81a1c1",
        "selected": "bold #88c0d0",
        "unselected": "#5e81ac",
        "tree.line": "#4c566a",
        "sexy_pink": "bold #b48ead"
    },
    "jungle-dim": {
        "info": "#8f9f8f",
        "warning": "#b0c0b0",
        "error": "bold #c58f8f",
        "success": "bold #8f9f8f",
        "site": "bold #a3b3a3",
        "title": "bold #c8d8c8",
        "count": "bold #a3b3a3",
        "menu": "#8f9f8f",
        "selected": "bold #a3b3a3",
        "unselected": "#5a6a5a",
        "tree.line": "#4a554a",
        "sexy_pink": "bold #8f9f8f"
    },
    "muted-lavender": {
        "info": "#957fb8",
        "warning": "#dcd7ba",
        "error": "bold #c34043",
        "success": "bold #76946a",
        "site": "bold #938aa9",
        "title": "bold #e5e0c8",
        "count": "bold #957fb8",
        "menu": "#938aa9",
        "selected": "bold #957fb8",
        "unselected": "#6e6080",
        "tree.line": "#494452",
        "sexy_pink": "bold #957fb8"
    },
    "dim-charcoal": {
        "info": "#8a8a8a",
        "warning": "#b0b0b0",
        "error": "bold #a07070",
        "success": "bold #809080",
        "site": "bold #a0a0a0",
        "title": "bold #dcdcdc",
        "count": "bold #b0b0b0",
        "menu": "#8a8a8a",
        "selected": "bold #c0c0c0",
        "unselected": "#606060",
        "tree.line": "#444444",
        "sexy_pink": "bold #909090"
    },
    "calm-ocean": {
        "info": "#87afd7",
        "warning": "#afd7ff",
        "error": "bold #c58585",
        "success": "bold #87afd7",
        "site": "bold #5f87a7",
        "title": "bold #d7ebff",
        "count": "bold #87afd7",
        "menu": "#5f87a7",
        "selected": "bold #87afd7",
        "unselected": "#4a6070",
        "tree.line": "#354555",
        "sexy_pink": "bold #87afd7"
    },
    "earthy-moss": {
        "info": "#afaf87",
        "warning": "#dfdfb8",
        "error": "bold #c59b9b",
        "success": "bold #87af87",
        "site": "bold #8f8f6f",
        "title": "bold #e5e5d0",
        "count": "bold #dfdfb8",
        "menu": "#8f8f6f",
        "selected": "bold #afaf87",
        "unselected": "#6b6b4f",
        "tree.line": "#4f4f35",
        "sexy_pink": "bold #afaf87"
    },
    "soft-sepia": {
        "info": "#dfaf87",
        "warning": "#dfd7af",
        "error": "bold #af7f7f",
        "success": "bold #afaf87",
        "site": "bold #af875f",
        "title": "bold #f0e6c8",
        "count": "bold #dfaf87",
        "menu": "#af875f",
        "selected": "bold #dfaf87",
        "unselected": "#6d5f50",
        "tree.line": "#4d3f35",
        "sexy_pink": "bold #dfaf87"
    },
    "dusk-rose": {
        "info": "#dfafc7",
        "warning": "bold #e0def4",
        "error": "bold #af7f8f",
        "success": "bold #af8797",
        "site": "bold #cba6f7",
        "title": "bold #ebd5e0",
        "count": "bold #dfafc7",
        "menu": "#af8797",
        "selected": "bold #dfafc7",
        "unselected": "#6e5560",
        "tree.line": "#4e3540",
        "sexy_pink": "bold #af8797"
    },
    "slate-storm": {
        "info": "#87afd7",
        "warning": "#afd7ff",
        "error": "bold #af7f7f",
        "success": "bold #5f8787",
        "site": "bold #5f8797",
        "title": "bold #dbe8f5",
        "count": "bold #87afd7",
        "menu": "#5f8797",
        "selected": "bold #87afd7",
        "unselected": "#4a5e6a",
        "tree.line": "#30404c",
        "sexy_pink": "bold #87afd7"
    },
    "night-sky": {
        "info": "#8787af",
        "warning": "#dfdfdf",
        "error": "bold #af7f7f",
        "success": "bold #5f8787",
        "site": "bold #5f5f87",
        "title": "bold #e5e5f0",
        "count": "bold #8787af",
        "menu": "#5f5f87",
        "selected": "bold #8787af",
        "unselected": "#555577",
        "tree.line": "#3d3d5c",
        "sexy_pink": "bold #8787af"
    },
    "sage-mist": {
        "info": "#9cb09d",
        "warning": "#c2cbbe",
        "error": "bold #b88a8a",
        "success": "bold #8ba88e",
        "site": "bold #a3b899",
        "title": "bold #e2e8e2",
        "count": "bold #c2cbbe",
        "menu": "#9cb09d",
        "selected": "bold #a3b899",
        "unselected": "#5f6e60",
        "tree.line": "#475448",
        "sexy_pink": "bold #a3b899"
    },
    "soft-zen": {
        "info": "#a0b2a6",
        "warning": "#d4cfb4",
        "error": "bold #ba8f8f",
        "success": "bold #94b09b",
        "site": "bold #b5a895",
        "title": "bold #e8e6df",
        "count": "bold #d4cfb4",
        "menu": "#a0b2a6",
        "selected": "bold #b5a895",
        "unselected": "#647068",
        "tree.line": "#4a544d",
        "sexy_pink": "bold #b5a895"
    },
    "cozy-warmth": {
        "info": "#d0a685",
        "warning": "#e6caad",
        "error": "bold #c48377",
        "success": "bold #b0ad87",
        "site": "bold #c79586",
        "title": "bold #f4eae1",
        "count": "bold #e6caad",
        "menu": "#d0a685",
        "selected": "bold #c79586",
        "unselected": "#7a6250",
        "tree.line": "#594739",
        "sexy_pink": "bold #c79586"
    },
    "twilight-fog": {
        "info": "#8e9ab0",
        "warning": "#b5c0d0",
        "error": "bold #b0808a",
        "success": "bold #8aa8a0",
        "site": "bold #9e8eb0",
        "title": "bold #e4e8f0",
        "count": "bold #b5c0d0",
        "menu": "#8e9ab0",
        "selected": "bold #9e8eb0",
        "unselected": "#556073",
        "tree.line": "#3f4757",
        "sexy_pink": "bold #9e8eb0"
    },
    "olive-branch": {
        "info": "#95a37f",
        "warning": "#c2cda8",
        "error": "bold #b58580",
        "success": "bold #829a6c",
        "site": "bold #a8b58a",
        "title": "bold #e6ebdb",
        "count": "bold #c2cda8",
        "menu": "#95a37f",
        "selected": "bold #a8b58a",
        "unselected": "#5a664a",
        "tree.line": "#424d35",
        "sexy_pink": "bold #a8b58a"
    },
    "autumn-forest": {
        "info": "#c69269",
        "warning": "#dfb689",
        "error": "bold #b86e65",
        "success": "bold #929d73",
        "site": "bold #ba7b65",
        "title": "bold #f0e6da",
        "count": "bold #dfb689",
        "menu": "#c69269",
        "selected": "bold #ba7b65",
        "unselected": "#73533b",
        "tree.line": "#543c29",
        "sexy_pink": "bold #ba7b65"
    },
    "gentle-indigo": {
        "info": "#7e8cb8",
        "warning": "#b0badb",
        "error": "bold #ab7585",
        "success": "bold #7ca69e",
        "site": "bold #8c7eb8",
        "title": "bold #e4e6f2",
        "count": "bold #b0badb",
        "menu": "#7e8cb8",
        "selected": "bold #8c7eb8",
        "unselected": "#4b5578",
        "tree.line": "#353d59",
        "sexy_pink": "bold #8c7eb8"
    },
    "whispering-teal": {
        "info": "#73a5a5",
        "warning": "#a5c9c9",
        "error": "bold #b27a80",
        "success": "bold #76a892",
        "site": "bold #7ba0b0",
        "title": "bold #e0eded",
        "count": "bold #a5c9c9",
        "menu": "#73a5a5",
        "selected": "bold #7ba0b0",
        "unselected": "#426666",
        "tree.line": "#2e4a4a",
        "sexy_pink": "bold #7ba0b0"
    },
    "muted-plum": {
        "info": "#968396",
        "warning": "#beadbe",
        "error": "bold #a86b77",
        "success": "bold #7fa08c",
        "site": "bold #9e739e",
        "title": "bold #eae2ea",
        "count": "bold #beadbe",
        "menu": "#968396",
        "selected": "bold #9e739e",
        "unselected": "#5e4e5e",
        "tree.line": "#453845",
        "sexy_pink": "bold #9e739e"
    },
    "sandstone-warm": {
        "info": "#bfa085",
        "warning": "#d9c4af",
        "error": "bold #b57a75",
        "success": "bold #9ca681",
        "site": "bold #b88d80",
        "title": "bold #f2eae4",
        "count": "bold #d9c4af",
        "menu": "#bfa085",
        "selected": "bold #b88d80",
        "unselected": "#705a48",
        "tree.line": "#544233",
        "sexy_pink": "bold #b88d80"
    },
    "misty-pines": {
        "info": "#7e968a",
        "warning": "#a9bdb3",
        "error": "bold #a37575",
        "success": "bold #73967d",
        "site": "bold #87997a",
        "title": "bold #e2e8e4",
        "count": "bold #a9bdb3",
        "menu": "#7e968a",
        "selected": "bold #87997a",
        "unselected": "#495b51",
        "tree.line": "#34423b",
        "sexy_pink": "bold #87997a"
    },
    "quiet-ember": {
        "info": "#bd8877",
        "warning": "#dbb29d",
        "error": "bold #b56763",
        "success": "bold #a69e7e",
        "site": "bold #b87b77",
        "title": "bold #f0e6e2",
        "count": "bold #dbb29d",
        "menu": "#bd8877",
        "selected": "bold #b87b77",
        "unselected": "#704b40",
        "tree.line": "#52362e",
        "sexy_pink": "bold #b87b77"
    },
    "sea-breeze": {
        "info": "#7aa3af",
        "warning": "#abcad3",
        "error": "bold #aa787e",
        "success": "bold #77a897",
        "site": "bold #6d93ab",
        "title": "bold #e4eff2",
        "count": "bold #abcad3",
        "menu": "#7aa3af",
        "selected": "bold #6d93ab",
        "unselected": "#446570",
        "tree.line": "#304b54",
        "sexy_pink": "bold #6d93ab"
    },
    "rose-quartz": {
        "info": "#b5989e",
        "warning": "#d9c5c9",
        "error": "bold #b5727e",
        "success": "bold #8f9b88",
        "site": "bold #b88a99",
        "title": "bold #f2e9ec",
        "count": "bold #d9c5c9",
        "menu": "#b5989e",
        "selected": "bold #b88a99",
        "unselected": "#6e565c",
        "tree.line": "#523d43",
        "sexy_pink": "bold #b88a99"
    },
    "velvet-dusk": {
        "info": "#8a7e96",
        "warning": "#b5abbf",
        "error": "bold #a66e7b",
        "success": "bold #7b9688",
        "site": "bold #917596",
        "title": "bold #e7e2eb",
        "count": "bold #b5abbf",
        "menu": "#8a7e96",
        "selected": "bold #917596",
        "unselected": "#52485c",
        "tree.line": "#3b3345",
        "sexy_pink": "bold #917596"
    },
    "silent-moon": {
        "info": "#8a94a6",
        "warning": "#b8c2d1",
        "error": "bold #a3757e",
        "success": "bold #7b9991",
        "site": "bold #848ca6",
        "title": "bold #e6ebf2",
        "count": "bold #b8c2d1",
        "menu": "#8a94a6",
        "selected": "bold #848ca6",
        "unselected": "#4f5869",
        "tree.line": "#383f4d",
        "sexy_pink": "bold #848ca6"
    },
    "frosted-glass": {
        "info": "#9eb3c2",
        "warning": "#c9d8e3",
        "error": "bold #b88a94",
        "success": "bold #8aa89c",
        "site": "bold #90a4b8",
        "title": "bold #f0f4f7",
        "count": "bold #c9d8e3",
        "menu": "#9eb3c2",
        "selected": "bold #90a4b8",
        "unselected": "#5c6d7a",
        "tree.line": "#42505c",
        "sexy_pink": "bold #90a4b8"
    },
    "pastel-midnight": {
        "info": "#7e8eb8",
        "warning": "#b2c0e0",
        "error": "bold #b87a8b",
        "success": "bold #7cb8a2",
        "site": "bold #a084b8",
        "title": "bold #e6ebf5",
        "count": "bold #b2c0e0",
        "menu": "#7e8eb8",
        "selected": "bold #a084b8",
        "unselected": "#4a577a",
        "tree.line": "#343d57",
        "sexy_pink": "bold #a084b8"
    },
    "warm-hazelnut": {
        "info": "#b5957a",
        "warning": "#dbbfab",
        "error": "bold #a86963",
        "success": "bold #919e7a",
        "site": "bold #ab7f6d",
        "title": "bold #f2eae4",
        "count": "bold #dbbfab",
        "menu": "#b5957a",
        "selected": "bold #ab7f6d",
        "unselected": "#6b513d",
        "tree.line": "#4e3a2b",
        "sexy_pink": "bold #ab7f6d"
    },
    "dusty-amber": {
        "info": "#c29e74",
        "warning": "#e3c6a3",
        "error": "bold #b87265",
        "success": "bold #9da378",
        "site": "bold #bd8a66",
        "title": "bold #f4eae0",
        "count": "bold #e3c6a3",
        "menu": "#c29e74",
        "selected": "bold #bd8a66",
        "unselected": "#75593c",
        "tree.line": "#574029",
        "sexy_pink": "bold #bd8a66"
    },
    "nordic-wood": {
        "info": "#9a9e87",
        "warning": "#c2c7ae",
        "error": "bold #a67272",
        "success": "bold #839e78",
        "site": "bold #949977",
        "title": "bold #e8ebdf",
        "count": "bold #c2c7ae",
        "menu": "#9a9e87",
        "selected": "bold #949977",
        "unselected": "#5d614d",
        "tree.line": "#434737",
        "sexy_pink": "bold #949977"
    },
    "mossy-stone": {
        "info": "#879987",
        "warning": "#adbfad",
        "error": "bold #9e7373",
        "success": "bold #739973",
        "site": "bold #859e85",
        "title": "bold #e2e8e2",
        "count": "bold #adbfad",
        "menu": "#879987",
        "selected": "bold #859e85",
        "unselected": "#506150",
        "tree.line": "#394739",
        "sexy_pink": "bold #859e85"
    },
    "peaceful-horizon": {
        "info": "#7da3b8",
        "warning": "#acc8d9",
        "error": "bold #b57a87",
        "success": "bold #7da89c",
        "site": "bold #7592b8",
        "title": "bold #e4eff5",
        "count": "bold #acc8d9",
        "menu": "#7da3b8",
        "selected": "bold #7592b8",
        "unselected": "#466375",
        "tree.line": "#304857",
        "sexy_pink": "bold #7592b8"
    },
    "soothing-emerald": {
        "info": "#74a892",
        "warning": "#a4c9b7",
        "error": "bold #ab7379",
        "success": "bold #6fa883",
        "site": "bold #699b8a",
        "title": "bold #e0f0e9",
        "count": "bold #a4c9b7",
        "menu": "#74a892",
        "selected": "bold #699b8a",
        "unselected": "#406957",
        "tree.line": "#2c4a3d",
        "sexy_pink": "bold #699b8a"
    },
    "calm-cobalt": {
        "info": "#7892b8",
        "warning": "#a8bee3",
        "error": "bold #b57885",
        "success": "bold #73a8a3",
        "site": "bold #6d84b8",
        "title": "bold #e4ebf7",
        "count": "bold #a8bee3",
        "menu": "#7892b8",
        "selected": "bold #6d84b8",
        "unselected": "#425778",
        "tree.line": "#2d3e57",
        "sexy_pink": "bold #6d84b8"
    },
    "mild-amethyst": {
        "info": "#917eb8",
        "warning": "#bcaee3",
        "error": "bold #b57588",
        "success": "bold #73a897",
        "site": "bold #8a6db8",
        "title": "bold #e9e4f7",
        "count": "bold #bcaee3",
        "menu": "#917eb8",
        "selected": "bold #8a6db8",
        "unselected": "#524378",
        "tree.line": "#392d57",
        "sexy_pink": "bold #8a6db8"
    },
    "soft-clay": {
        "info": "#b88a7d",
        "warning": "#e3b5a8",
        "error": "bold #b56965",
        "success": "bold #99a880",
        "site": "bold #b87b70",
        "title": "bold #f5eae6",
        "count": "bold #e3b5a8",
        "menu": "#b88a7d",
        "selected": "bold #b87b70",
        "unselected": "#6e4d44",
        "tree.line": "#4f362f",
        "sexy_pink": "bold #b87b70"
    },
    "deep-silence": {
        "info": "#788796",
        "warning": "#a4b5c7",
        "error": "bold #996e76",
        "success": "bold #6e8e84",
        "site": "bold #727b96",
        "title": "bold #dfdbe8",
        "count": "bold #a4b5c7",
        "menu": "#788796",
        "selected": "bold #727b96",
        "unselected": "#434d57",
        "tree.line": "#2c333b",
        "sexy_pink": "bold #727b96"
    },
    "winter-hearth": {
        "info": "#bd9a80",
        "warning": "#e0c3ab",
        "error": "bold #b56e67",
        "success": "bold #8fa882",
        "site": "bold #b88674",
        "title": "bold #f4ebe1",
        "count": "bold #e0c3ab",
        "menu": "#bd9a80",
        "selected": "bold #b88674",
        "unselected": "#6e5442",
        "tree.line": "#4f3a2c",
        "sexy_pink": "bold #b88674"
    },
    "soft-monochrome": {
        "info": "#999999",
        "warning": "#cccccc",
        "error": "bold #b88888",
        "success": "bold #99b899",
        "site": "bold #bbbbbb",
        "title": "bold #eeeeee",
        "count": "bold #cccccc",
        "menu": "#aaaaaa",
        "selected": "bold #ffffff",
        "unselected": "#555555",
        "tree.line": "#333333",
        "sexy_pink": "bold #dddddd"
    }
}
